version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: it610

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build: php-apache-mysqli
    ports:
      - 8888:80
    volumes:
      - ./html:/var/www/html/